name: Feature request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ['enhancement']

body:
- type: 'markdown'
  attributes:
    value: |-
      Thank you for requesting a feature. Please complete the form below so we can triage and prioritize your feature.

- id: 'tldr'
  type: 'textarea'
  attributes:
    label: 'TL;DR'
    description: 'Describe the feature in 1-2 sentences.'
  validations:
    required: true

- id: 'tf_resources'
  type: 'textarea'
  attributes:
    label: 'Terraform Resources'
    description: 'If provider resources are available, please include links to the provider documentation.'
    render: 'markdown'

- id: 'detailed_design'
  type: 'textarea'
  attributes:
    label: 'Detailed design'
    description: 'Do you have more information about a detailed design? Are there specific considerations to take? Include sample configuration if possible.'
    render: 'markdown'

- id: 'additional'
  type: 'textarea'
  attributes:
    label: 'Additional information'
    description: 'Is there anything else you think we should know?'